name: ensend_flutter
description: >-
  The official Dart/Flutter SDK for the Ensend multi-channel notification and
  messaging platform. Supports transactional email, email broadcasts, and SMTP.
version: 0.1.0
homepage: https://docs.ensend.co
repository: https://github.com/ensend/ensend-dart

environment:
  sdk: ^3.0.0

platforms:
  android:
  ios:
  web:

dependencies:
  http: ^1.2.0
  dio: ^5.8.0
  meta: ^1.9.0
  logger: ^2.8.0

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0
  mocktail: ^1.0.3
  coverage: ^1.9.0
